### ISSUE TITLE
Roadmap for v0.3

### ISSUE THREAD

**Issue by sbarral** [asynchronics/nexosim#50]
### Development branch

The development branch for `v0.3` is `main`.

### Crate rename warning

Due to common confusion between *asynchronics* and *asynchronix*, version `v0.3` of asynchronix ~will be renamed to a TBD name~ was renamed to `nexosim`. 

### Tentative timeline

- beta release deadline: 2024-11-17 -- DONE :tada: :partying_face: 
- official release deadline: ~2024-12-31~ 2025-01-20 -- DONE :tada: :partying_face:  (Python front-end to be release separately by ~end 2025-02~ mid 2025-03)

~The beta release is expected to be API-complete and production-ready, but will lack presumably up-to-date documentation and the Python client may not be completed yet.~

## Roadmap

- [x] add a single-threaded executor supporting compilation to WebAssembly [#1, closed by #24]
- [x] add a gRPC server for remote execution and all surrounding infrastructure [closed by #12, #24, #25, #26, #29, #43; incidentally closes #16]
- [x] add support for the `tracing` crate [closed by #47]
- [x] make `Output` and `Requestor` `Clone`-able [closed by #30, #48 ] 
- [x] make the global `Scheduler` an owned `Clone`-able type [closed by #30] 
- [x] add an automatically managed action key for scheduled actions/events [closed by #27]
- [x] simplify "impedance matching" between models using similar but different input/output types with `map_connect()` methods on `Output` and `Requestor` [closed by #32]
- [x] streamline the creation of buses such as SPI, CAN, MIL-STD-1553, SpaceWire etc. with `filter_map_connect()` methods on `Output` and `Requestor` [closed by #32]
- [x] add a gRPC-based Python client [~release date: 2025-04-23~released on 2025-04-23!]
- [x] provide additional ordering guaranties when using the global scheduler [#34, closed by #62] 
- [x] implement deadlock detection [#28, closed by #51] 
- [x] implement execution timeout [#28, closed by #57] 
- [x] catch model panics and report them as errors (merged with: make it possible to abort the simulation from a model with an arbitrary error payload) [#22, closed by #60]
- [x] streamline the builder pattern for models with a `ProtoModel` trait [closed by #54]
- [x] ~add an `async send()` method on `Address`~ [*no longer planned*]
- [x] return an error when the simulation clock looses synchronization [closed by #58]

**Comment by Ben-PH** [comment]
With 3.x released, is this issue ready for close. If not, it might be useful to communicate this prominently in the issue description.

**Comment by sbarral** [comment]
Yes, 0.3.0 has been out already a couple of month so it's admittedly confusing: I left this issue open only because the long-awaited Python wrapper is not yet officially out (sorry!)...

`NeXosim-py` is now considered ready and will come with a nice [user guide and API ref](https://nexosim-py.readthedocs.io/en/latest/), we just wanted to give ourselves a couple days more just in case. It will be released on PyPi on April 23rd, at which time I will close this issue.

**Comment by sbarral** [comment]
[NeXosim-py](https://nexosim-py.readthedocs.io/) is out! This closes the last item.
